### ISSUE TITLE
益书网不能下载

### ISSUE THREAD

**Issue by dupontjoy** [jingyu9575/multithreaded-download-manager#10]
https://kindbook.cn/forum.php?mod=viewthread&tid=59948&highlight=%BA%DA%CF%BB%D7%D3%CB%BC%CE%AC
![3](https://user-images.githubusercontent.com/4965288/35326047-7085d9f6-0130-11e8-8f2e-d77952461af2.jpg)
点击下载后, 弹窗接管, 但是每次都只能下载几十K, 没有下载到全本书

**Comment by jingyu9575** [comment]
无法测试：
![default](https://user-images.githubusercontent.com/8923139/35328349-5e50bfda-013f-11e8-83f2-ff6ead90981d.png)

![default](https://user-images.githubusercontent.com/8923139/35328196-e5f37c1c-013e-11e8-9321-a9f4fcfcae2a.png)

不过，网站提示了“勿用迅雷，浏览器关闭下载加速”，很可能服务器会检测、封杀多线程下载，这就很难在扩展中解决了。

**Comment by dupontjoy** [comment]
有没有微信啥的, 我把账号给你测试下

**Comment by jingyu9575** [comment]
我用签到的1个币测试了下，确实下载了一个几十KB的文件，但内容不是电子书的一部分，而是一个网页（HTML）：

> 今日下载次数已达到限制值(1次/天),请明天再来看看吧...

你的帐号是否也有下载次数限制？请将下载的错误文件改扩展名为html，双击查看内容。
另外，使用这个扩展可能会消耗 线程数+1 点下载次数，因为[多线程会重复计算](https://kindbook.cn/forum.php?mod=viewthread&tid=23153&extra=page%3D1)，而且根据这次测试，弹窗接管的这个连接似乎也算在内了。

**Comment by dupontjoy** [comment]
我的账号没有次数限制, 加我微信: dupontjoy, 我给你账号吧

**Comment by jingyu9575** [comment]
在我这里下载没有这个问题。
从微信讨论中发现，使用全新配置下载正常，出问题时下载得到的文件是HTML网页：
![screenshot_20180127_212007](https://user-images.githubusercontent.com/8923139/35472116-7771d8f4-03ac-11e8-88a2-445356b43e29.png)
看起来登录状态在下载时丢失了。这可能和其他扩展或隐私设置有关。
