### ISSUE TITLE
Extension windows

### ISSUE THREAD

**Issue by wvxwxvw** [jingyu9575/multithreaded-download-manager#102]
Extension windows you need to assign the attribute "over Firefox window". A little gape, clicked outside the browser or moved to another tab and that's all. All the Windows of your extension hang invisible background.

**Comment by jingyu9575** [comment]
Firefox extensions cannot assign this attribute to extension windows. However, we can emulate this, by switching to extension windows whenever the browser is focused.

v2.6 will have this option, in the "advanced" page.
