### ISSUE TITLE
Add the setting to automatically download in the m-d-m

### ISSUE THREAD

**Issue by wvxwxvw** [jingyu9575/multithreaded-download-manager#109]
For selecting "Automatically prompt for download:" add a third option "Download without request".
I. e. there should be three options: 1. directly, 2. request, 3. without a request (i.e. directly through the extension).

Many will want to use the Manager for all links, because of the squalid built-in Firefox downloads page. Do not keep the same two extensions for downloads? In this case, all these unnecessary questions to anything.

**Comment by jingyu9575** [comment]
If you choose *directly*, it will be through the extension. 

There is no option to use the built-in download directly. I think most users of this extension won't want such an option.
