### ISSUE TITLE
Change extension tab title

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#111]
@jingyu9575 what you think change the  extension tab title to just MDM, I think it can help to differentiate the extension tab to the sites tabs, is just an suggestion

**Comment by wvxwxvw** [comment]
=) Only two days ago I told the author about it. For the Russian language, I It changed.

**Comment by jingyu9575** [comment]
Yes it is a problem. I was not aware of it as I'm using the Chinese version, and the Chinese title is not so long. However, I think it is too late to make such a UI change. Probably adding an option is better.

**Comment by jingyu9575** [comment]
An option is added.
