### ISSUE TITLE
Extremely Quick Download Mode

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#113]
My idea is add an feature to download extremely quick direct links, for instance sometimes we are browsing lots of image galleries and picking some of images of the galeries but not all images of the gallery, just selected images, of many tabs, maybe 50 tabs, so with the new feature I can just use "alt + left click in any thumbnail" to add this image on download list silently without any warning and without open this image in an tab, this is useful because today I need open this images in browser to after save it with extensions or copy the tabs links list to after import it to MDM, sometimes I have 150 images in 150 tabs, is a lot of memory and browser restarts e even some crashes, with this feature I can open in tabs just the galleries but not the images, the images can go directly to MDM, is an much light and smart work, this can be useful also to all direct links picking works, mass works with direct links, no just images, like pages with a lot of zips or rars, mp3, etc,

**Comment by RanHum** [comment]
You can use [Imagus](https://addons.mozilla.org/en-US/firefox/addon/imagus/) for images, and for archives it's more suitable to combine [FoxyLink](https://addons.mozilla.org/en-US/firefox/addon/foxylink/) with proper standalone DM (for example usecase, can't say about all), only collection of filters and heuristics like in imagus can properly obtain images from thumbnails, and it's quite out of scope of this extension to integrate this, imho. I think, it COULD be done in [DownThemAll!](https://github.com/downthemall/downthemall) in the future, though

**Comment by Mike-Reddick** [comment]
No! Imagus is for enlarge thumbnails with a mouse hover, I want not enlarge thumbnails but download, and FoxyLink I have this extension, but is other completely different function, I don't want download one image I often download hundreds, thousands, and I don't want select ALL images from an gallery sequentially with mouse drag, but for instance in an gallery with 15 images I want just 4 in different places, and I have sometimes 100 galleries to work, so FoxyLink context menu isn't productive .

**Comment by RanHum** [comment]
Oh, my bad, I haven't mention Ctrl+S for download in imagus. Personally, i use imagus for galleries with this quick-save-what-you-see-feature, and [GlitterDrag](https://addons.mozilla.org/en-US/firefox/addon/glitterdrag/) configured to download any link click-holded and dragged down, perhaps, it's less snappy than you need, and I don't really know already-existing appropriate solution for that, but at least I tried to share some information...

**Comment by Mike-Reddick** [comment]
In the past I used an drag extension to download, but now with WebExtensions I can't find some alternatives, because of poor extensions descriptions somestimes, I think the Alt + Left Click solution more quick and easy than drag, if you see the big volume I work, I think be an good and simple feature to be implemented, I don't know if is possible, but I can use this GlitterDrag as an solution for now, thanks for share!
