### ISSUE TITLE
Impossible to download

### ISSUE THREAD

**Issue by happysurf** [jingyu9575/multithreaded-download-manager#115]
Recently I tried to dowload some video files like this https://wssd11.fastcdn.stream/lnholpcsgt5ee35huuq2cl5zi7ebo3sibmhnoj5pl3axmu3c5fyorks5q2vq/v.mp4 without success.
Any thoughts?

**Comment by jingyu9575** [comment]
Looks like the server will give errors if multi-threading is used. I'm unable to get anything more than 2 threads, and sometimes even opening the link in the browser will show errors. 
I don't know whether it is intentional. Probably it is better to just use 1 thread.
