### ISSUE TITLE
Batch Retry Failed Downloads

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#116]
I want ask, an easy way, an context menu entry or button, to retry "all failed downloads" sometimes we have an big download list and have some issue with internet, or with the remote server, temporally offline, then you got an big list with a lot of failed downloads and need retry one by one.

More one time, thanks and congratulations for this extension!

**Comment by jingyu9575** [comment]
With #110 implemented, it is possible to resume all tasks with *select all - start*. This will also start all paused tasks though. Is it OK for your use case?

**Comment by Mike-Reddick** [comment]
Perfect!
