### ISSUE TITLE
在Firefox 72上面不能接管内置的下载管理器

### ISSUE THREAD

**Issue by dxvgef** [jingyu9575/multithreaded-download-manager#117]
因为这个问题所以我把扩展暂时禁用了，我记得在firefox更新之前是好的。

**Comment by jingyu9575** [comment]
在我这里 Firefox 72.0.1 / Windows x64 是正常的，具体是什么现象？

**Comment by dxvgef** [comment]
不知道怎么现在又好了，就是有一阵子无法接管浏览器自带的下载。好像扩展完全不存在一样。我的是firefox 72.0.1/mac os
________________________________
发件人: jingyu9575 <notifications@github.com>
发送时间: 2020年1月15日 22:46
收件人: jingyu9575/multithreaded-download-manager <multithreaded-download-manager@noreply.github.com>
抄送: dxvgef <dxvgef@outlook.com>; Author <author@noreply.github.com>
主题: Re: [jingyu9575/multithreaded-download-manager] 在Firefox 72上面不能接管内置的下载管理器 (#117)


在我这里 Firefox 72.0.1 / Windows x64 是正常的，具体是什么现象？

―

**Comment by dxvgef** [comment]
又出现了，我电脑首次启动firefox，第一次触发下载时，扩展不能接替firefox内置的下载管理器。

**Comment by dxvgef** [comment]
你可以试试这个软件的天翼网盘的下载，好像怎么都调用不了扩展，只能用内置的下载管理器。
https://www.macwk.com/soft/navicat-premium

**Comment by jingyu9575** [comment]
我现在这个手机号没法注册天翼网盘。有可能是服务器不支持多线程，默认扩展不接管这类链接。
