### ISSUE TITLE
capture download from another extensions

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#119]
Is possible implement capture download from another extensions? Like downloads from Glitter Drag and others?

**Comment by Mike-Reddick** [comment]
@jingyu9575 thanks the attention, but what I said is not to capture videos from streamings, like youtube, but capture downloads from another extensions, example, the Glitter Drag extension, with this extension when you drag an link, the link is added to native download manager, is possible capture this link to add it to MDM?

**Comment by jingyu9575** [comment]
Yes they are using another extension to download YouTube links, and requests capture downloads from that extension. 
I think it is possible, although the built-in download must be stopped and imported into the extension. If the link can only be accessed once, it will be broken.

**Comment by Mike-Reddick** [comment]
I understand, thanks again

**Comment by jingyu9575** [comment]
This feature is added in v2.8b1. Please see if it works for your use case.

**Comment by Mike-Reddick** [comment]
First I want thanks, all the last changes, third-party favicon of tab change without any delay, setting to rename tab, selected item in dark mode, all is working very fine! I tried, I click "automatically import from other extensions", then open the monitor popup, then I make an download using "Glitter Drag" extension, dragging an image, the image go to build-in manager, and show nothing in monitor popup, maybe I'm doing something wrong?  Thanks

**Comment by Mike-Reddick** [comment]
@jingyu9575 I'm doing something wrong? Sorry if I'm asking you in an wrong time.

Thanks

**Comment by jingyu9575** [comment]
This is what I get:

![VgRU3INDjc](https://user-images.githubusercontent.com/8923139/73878418-c9e97c00-485a-11ea-8322-5cdf452b25d7.gif)

**Comment by Mike-Reddick** [comment]
Really to you worked well, I'm using the minimum Firefox version required by MDM, FF 67, because this is the last FF which have single process mode in about:config, I need single process because of low amount of memory. Maybe this feature use new APIs?

**Comment by jingyu9575** [comment]
I just tested with Firefox 67 and it does not work. It turns out that the API is only supported on [Firefox 69+](https://bugzilla.mozilla.org/show_bug.cgi?id=1305663). I am not aware of any workaround now.

It seems that single process can be enabled in Firefox 72 by setting a environment variable `MOZ_FORCE_DISABLE_E10S` to `1`.

**Comment by jingyu9575** [comment]
Without e10s (and webext-oop), the extension (v2 method) requires an additional copy in the temporary storage, to workaround a Firefox bug. 
In the latest Firefox it is possible to set the number of content processes in options. If the memory usage is acceptable after decreasing the option, I would suggest it instead of turning off e10s.

**Comment by Mike-Reddick** [comment]
> In the latest Firefox it is possible to set the number of content processes in options

I tried it before but FF continue using more processes and memory, the only way to use only one process is disabling E10S. 

I'm using FF 67 also because of a lot of custom UI CSS's (userChrome)  :)  but I'm thinking maybe update to FF 72 someday, but anyway thanks the attention, the reply and all explanations. Thanks so much.

**Comment by Mike-Reddick** [comment]
> Without e10s (and webext-oop), the extension (v2 method) requires an additional copy in the temporary storage, to workaround a Firefox bug

@jingyu9575  using the new segmented mode without e10s (and webext-oop),  requires an additional copy in the temporary storage?

**Comment by jingyu9575** [comment]
No, the segmented mode uses only standard features and does not require such workaround.

**Comment by Mike-Reddick** [comment]
@jingyu9575, thanks, I'm doing some tests with segmented mode, but I tested with very long writing intervals, to reduce HD wear, I know with long intervals I lost more download progress, but I never close browser with running downloads anyway, but with long intervals download stop many times and need pause-start to resume, then I'm using old method again.
