### ISSUE TITLE
Problem in loading dialog boxes of 'Create a download task' and 'Import tasks from the build-in download list'

### ISSUE THREAD

**Issue by zhaiyusci** [jingyu9575/multithreaded-download-manager#12]
Dear all,    
I really appreciate what you have done in this add-on for the community.  However, I run into a problem that when I click 'Create a download task' or 'Import tasks from the build-in download list' in the pop-up of this add-on, I get blank dialog boxes.  However after I change the size of the dialog boxes a little bit, the contents show up.

What system I am using:
      User Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0`
      OS: `Linux 4.13.0-32-generic`, Linux Mint 18.3 'Sylvia' Cinnamon 64-bit

Would you please fix it? 

Sincerely yours,
Yu

**Comment by jingyu9575** [comment]
This is one of Firefox's bugs when "out of process extensions" is disabled. [Read more](https://github.com/jingyu9575/multithreaded-download-manager/wiki/Problems-with-disabling-the-feature-%22out-of-process-extensions%22)

From Firefox's bug tracker, it is said that changing the size automatically can workaround this bug. I will try it after the current work on #7.

**Comment by jingyu9575** [comment]
An option to change the size automatically has been added to v1.0a2. As Firefox is working toward enabling "out of process extensions", this problem will go away eventually.
