### ISSUE TITLE
capture link of others types

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#120]
for instance links from www.tubeoffline.com, in this case the extension can't capture the link and browser open as streaming in an tab

**Comment by jingyu9575** [comment]
For audios, an option *Enable prompt for audio files* is already added in #114. I've added another similar option for videos.

It does not capture them by default, to prevent conflict with streaming.

**Comment by Mike-Reddick** [comment]
thanks so much!
