### ISSUE TITLE
Option for Auto Prompt

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#121]
When using Automatically prompt for download => Direct Download, add an option to when hold ALT toggle to Ask for options.

**Comment by jingyu9575** [comment]
It is not possible to *Alt*-click a link in Firefox. It will allow users to select link text instead.
Also, *Shift* will open in new window and *Ctrl* will open in new tab.

**Comment by Mike-Reddick** [comment]
maybe ctrl + alt + click ? :)

**Comment by jingyu9575** [comment]
*Ctrl+Alt* also opens in a new tab like *Ctrl*. This is not easy because the automatic prompt works in the connection level, and the keyboard state is not recorded with the connections. I'll think about it.

**Comment by Mike-Reddick** [comment]
I closed it because the user can set:

Automatically prompt for download => Direct Download
Add a context menu to link => Ask for options

thanks so much
