### ISSUE TITLE
"Enable prompt for video files" option do not working !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#124]
Hi. I tested the new option "Enable prompt for video files" & it is not working on the following link:
https://archive.org/details/electricsheep-flock-244-80000-7

There is on your right hand an "OGG VIDEO" & "H.264". Each of them contain 89 files. The "OGG VIDEO" is for .ogv files, while "H.264" is for .mp4 files. Currently, your great add-on fail to capture any of these individual files (whether .ogv or .mp4) when click download link for any of them individually.

Please your kind fix for this

**Comment by jingyu9575** [comment]
These links work here. What values did you set to the option *Disable for files smaller than:* about the automatic prompt?

**Comment by Nokia808** [comment]
@jingyu9575 
The default value: 1024 KB. 
I changed it to be set at zero & it worked !
I will close this.
