### ISSUE TITLE
"大小错误"

### ISSUE THREAD

**Issue by xtsteven** [jingyu9575/multithreaded-download-manager#127]
不止下面这一个链接，都有提示大小错误，而无法下载
http://dl.maxthon.cn/mx5/maxthon_portable_5.3.8.2000.7z
其他插件有 AdGuard LightProxy

**Comment by jingyu9575** [comment]
在我这里没有问题。请在扩展选项中设置 *高级*-*日志级别* 为 *信息*，重新下载有错误的文件，右键单击任务查看日志，将原始日志复制上来。

> LightProxy

可能是代理的问题，你用的是什么代理？

**Comment by xtsteven** [comment]
代理我没有开，然后上面的地址突然的就好了…………  
试试这个地址: http://dl.maxthon.cn/mac5/Maxthon-r5.1.134.180827.dmg
插件设置中，就设置了 动态最小块长
[
	{
		"level": "info",
		"message": "创建任务 16",
		"date": "2020-01-20T00:43:33.371Z",
		"line": "/background/multithreaded-task.js:108:21",
		"extra": {
			"type": "MultithreadedTask",
			"state": "downloading",
			"creationDate": "2020-01-20T00:43:33.368Z",
			"inum": 1,
			"url": "http://dl.maxthon.cn/mac5/Maxthon-r5.1.134.180827.dmg",
			"filenameTemplate": "Maxthon-r5.1.134.180827.dmg",
			"referrer": "https://www.maxthon.cn/mx5/",
			"checksum": "",
			"maxThreads": "4",
			"minChunkSize": "1024",
			"maxRetries": "5",
			"filename": "Maxthon-r5.1.134.180827.dmg"
		}
	},
	{
		"level": "info",
		"message": "开始下载 http://dl.maxthon.cn/mac5/Maxthon-r5.1.134.180827.dmg",
		"date": "2020-01-20T00:43:33.376Z",
		"line": "/background/multithreaded-task.js:158:21"
	},
	{
		"level": "info",
		"message": "连接 API：StreamsConnection",
		"date": "2020-01-20T00:43:33.376Z",
		"line": "/background/multithreaded-task.js:159:21"
	},
	{
		"level": "info",
		"message": "创建连接，位置：0",
		"date": "2020-01-20T00:43:33.376Z",
		"line": "/background/multithreaded-task.js:222:21"
	},
	{
		"level": "info",
		"message": "建立初始连接。总大小：22026483；多线程支持：是",
		"date": "2020-01-20T00:43:33.629Z",
		"line": "/background/multithreaded-task.js:188:25",
		"extra": {
			"finalURL": "http://dl.maxthon.cn/mac5/Maxthon-r5.1.134.180827.dmg",
			"acceptRanges": true,
			"totalSize": 22026483
		}
	},
	{
		"level": "info",
		"message": "创建连接，位置：5506620",
		"date": "2020-01-20T00:43:33.633Z",
		"line": "/background/multithreaded-task.js:222:21"
	},
	{
		"level": "info",
		"message": "创建连接，位置：11013240",
		"date": "2020-01-20T00:43:33.634Z",
		"line": "/background/multithreaded-task.js:222:21"
	},
	{
		"level": "info",
		"message": "创建连接，位置：16519860",
		"date": "2020-01-20T00:43:33.635Z",
		"line": "/background/multithreaded-task.js:222:21"
	},
	{
		"level": "info",
		"message": "连接终止",
		"date": "2020-01-20T00:43:33.808Z",
		"line": "/background/multithreaded-task.js:325:21",
		"extra": {
			"name": "ReportedError",
			"message": "大小错误",
			"stack": "ExtendableError@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/util/error.js:3:9\nReportedError@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/util/error.js:33:9\nConnection/this.info<@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:59:42\n"
		}
	},
	{
		"level": "error",
		"message": "大小错误: 22026483",
		"date": "2020-01-20T00:43:33.810Z",
		"line": "/background/multithreaded-task.js:547:21",
		"extra": 22026483,
		"stack": [
			"fail@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:547:21",
			"onConnectionComplete@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:348:29"
		]
	},
	{
		"level": "info",
		"message": "连接终止",
		"date": "2020-01-20T00:43:33.828Z",
		"line": "/background/multithreaded-task.js:325:21",
		"extra": {
			"name": "AbortError",
			"message": "The operation was aborted. ",
			"stack": "abortError@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/util/error.js:18:12\nonStopped@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:98:30\n"
		}
	},
	{
		"level": "info",
		"message": "连接终止",
		"date": "2020-01-20T00:43:33.828Z",
		"line": "/background/multithreaded-task.js:325:21",
		"extra": {
			"name": "AbortError",
			"message": "The operation was aborted. ",
			"stack": "abort@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:80:31\nabort@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:168:15\nremoveAllConnections@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:494:24\nfail@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:550:14\nonConnectionComplete@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:348:29\n"
		}
	},
	{
		"level": "info",
		"message": "连接终止",
		"date": "2020-01-20T00:43:33.828Z",
		"line": "/background/multithreaded-task.js:325:21",
		"extra": {
			"name": "AbortError",
			"message": "The operation was aborted. ",
			"stack": "abort@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:80:31\nabort@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/connection.js:168:15\nremoveAllConnections@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:494:24\nfail@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:550:14\nonConnectionComplete@moz-extension://875b96a8-3826-41c3-8425-ec615721fa71/background/multithreaded-task.js:348:29\n"
		}
	}
]
