### ISSUE TITLE
Brazilian Portuguese Translation (uploaded)

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#131]
Here is the complete Brazilian Portuguese Translation (Portugues do Brasil, PT-BR) for version 3.1b1. @jingyu9575 feel free to use it on your extension if you want.

https://www.mediafire.com/file/zwlwbkz7v6mesyv/PT-BR__Translation.txt/file

**Comment by Mike-Reddick** [comment]
Feel free to use it on Mozilla "store" as description:

Essa extensão pode fazer download de arquivos usando múltiplas conexões no servidor. Dependendo da condição da rede, isso pode aumentar a velocidade do download.

Primeiros Passos:

    Se mais de 6 conexões for necessário, abra o about:config, e aumente os valores do "network.http.max-persistent-connections-per-server" e  "network.http.max-persistent-connections-per-proxy".
    Tenha certeza de ter espaço suficiente no disco. Os arquivos precisam ser colocados primeiro no no armazenamento interno do Firefox.


Essa extensão não coleta ou envia seus dados. As permissões requeridas são explicadas no Privacidade e Permissões.

**Comment by jingyu9575** [comment]
Thank you! It has been included in version 3.1b2.

The file is added [here](https://github.com/jingyu9575/multithreaded-download-manager/blob/master/src/_locales/pt_BR/messages.cson). If you find any issues, you can edit it and create a pull request.
