### ISSUE TITLE
[Translation] Adding French translation

### ISSUE THREAD

**Issue by xerta555** [jingyu9575/multithreaded-download-manager#14]
Hello,

Here is the french translation for this firefox module.
[messages.zip](https://github.com/jingyu9575/multithreaded-download-manager/files/1758820/messages.zip)

You can add the file in the ZIP file into your project.

Cordially

**Comment by jingyu9575** [comment]
Added to v1.2a3 (`fr`). Thank you!

I have made some modifications:
1. The symbol `'` conflicts with the structure `message: '...'`. I have changed the structure to `message: "..."` to avoid the conflict.
2. This option deals with some websites that give encoded filename like `%20%45`. I have changed back the example from '20%' to '%20'.
> Détecter le pourcentage d'encodage (par exemple %20)
