### ISSUE TITLE
Download added as paused when hitting enter

### ISSUE THREAD

**Issue by Jed28** [jingyu9575/multithreaded-download-manager#141]
After entering a filename if you press enter it always adds the download in a paused state.
To reproduce: click add download task -> put any text in filename -> hit enter.
I was using a download link from my clipboard, no idea if that's relevant.

**Comment by jingyu9575** [comment]
It is not paused on my system. Are you using Windows or Linux?

**Comment by Jed28** [comment]
Linux OS. I just checked in windows and it isn't added as a paused state.

**Comment by jingyu9575** [comment]
Yes the button order on Linux is different, and the *Add paused* button becomes the first affirmative button. Try the new version.

**Comment by Jed28** [comment]
Thanks, worked perfectly.
