### ISSUE TITLE
Option to get remote timestamps

### ISSUE THREAD

**Issue by M86xKC** [jingyu9575/multithreaded-download-manager#143]
This is a very useful feature when downloading multiple files with identical names, or checking if the file has change since last downloaded. It retrieves timestamp of the remote file from the remote HTTP/FTP server and if it is available, apply it to the local file.

here is more information:
https://aria2.github.io/manual/en/html/aria2c.html#cmdoption-r
http://www.gnu.org/software/wget/manual/wget.html#Time_002dStamping

**Comment by jingyu9575** [comment]
This has been mentioned in #28 (in Chinese).

Unfortunately, Firefox does not allow extensions to set the downloaded file time.
