### ISSUE TITLE
[Translation] Update for French translation

### ISSUE THREAD

**Issue by xerta555** [jingyu9575/multithreaded-download-manager#15]
Hello,

I have tested your extension, globally it works good.
Also i have update the French translation by respecting your fix:
[https://github.com/jingyu9575/multithreaded-download-manager/issues/14](https://github.com/jingyu9575/multithreaded-download-manager/issues/14)

Here is the updated file:
[messages.zip](https://github.com/jingyu9575/multithreaded-download-manager/files/1763911/messages.zip)

Also, i don't see fr folder in the "/src/_locales/" folder, i thik u will ad soon as possible..

Best regards for this FF addon.

**Comment by jingyu9575** [comment]
Merged to v1.2a4. Thank you!
Yesterday I forgot to push (upload the changes). Now I have pushed this folder. Sorry for the confusion.

**Comment by xerta555** [comment]
Ah great!
