### ISSUE TITLE
Cannot expand drop-down list in add-on options when installed on Firefox Developer Edition

### ISSUE THREAD

**Issue by mo-han** [jingyu9575/multithreaded-download-manager#151]
Windows 10 LTSB 2016 64-Bit
Firefox Developer Edition 78.0b9

Drop-down list like this cannot be clicked
![image](https://user-images.githubusercontent.com/9916948/85940866-b5b13300-b951-11ea-8fb2-568af161132e.png)

**Comment by jingyu9575** [comment]
This should be a problem of Firefox; such drop-down does not work in other extensions either.

Looks like it is already fixed in today's Nightly. Let's see what happens when Firefox 78 releases.

**Comment by jingyu9575** [comment]
Fortunately it seems to be fixed on Firefox 78 release and ESR.
