### ISSUE TITLE
Size Error

### ISSUE THREAD

**Issue by cyberfunk** [jingyu9575/multithreaded-download-manager#158]
My downloads get to about 99.9% finished then I get this error. Can anyone help me diagnose?

![Screen Shot 2020-09-27 at 11 04 28 PM](https://user-images.githubusercontent.com/12664589/94396066-f87fd400-0115-11eb-873e-042d3779dcf1.jpg)

**Comment by jingyu9575** [comment]
This error could be caused by incorrectly configured servers. The parts do not agree with each other (in size), and the extension shows an error instead of combining them into an incorrect file.

What's the file's URL?

**Comment by cyberfunk** [comment]
The files are hosted at uploaded.net I had a premium account which allows the use of a download manager. I will try to find another large file hosted at another site and do a test to see if the error is specific to uploaded.net

**Comment by cyberfunk** [comment]
I just did a test with a download from my own website and it worked fine. I think uploaded.net have their servers configured for optimal security so it's throwing a monkey wrench in downloading extensions. I can't even get their links to trigger multi-threaded downloader's link catching feature and I have to transfer downloads from the native FireFox downloader which is inconvenient. They mask their links with java script handlers instead of a direct link.
