### ISSUE TITLE
Failure to download from this site !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#164]
Hi. 

Kindly test these links:
https://nitroflare.com/view/97485461CB5DE92/0199664366.pdf
https://nitroflare.com/view/52FC7B26ACCC6FD/B01BZ30186.pdf

By the way: this add on did not receive any update since long time ! I would like to ask, is it still maintained or it is in death state ?

**Comment by jingyu9575** [comment]
It is working on my system. The server does not support multi-threading, so it will only be captured if both *PDF* and *Enable prompt for links without multithreading support* are checked.

![图片](https://user-images.githubusercontent.com/8923139/104944247-e2ae5b80-59f1-11eb-9dc7-7993eef335e0.png)

**Comment by jingyu9575** [comment]
I am a little busy right now, and do not have much time for side projects. I still use the extension myself and will at least keep it compatible and without major bugs.

**Comment by Nokia808** [comment]
@jingyu9575 
No ! It does not work ! I'm already set add-on as you instructed. On my system I'm also see this window that you screenshot. But the downloaded file NOT same file ! Do you downloaded file & opened it ? I'm suspicious that you did this.

I tried the following link:
https://nitroflare.com/view/52FC7B26ACCC6FD/B01BZ30186.pdf
the size of pdf is 50.37 MB but the downloaded file is just 5.7 KB. I attached it. Open it & see by yourself !

I'm on Fedora Linux 32 X64 bit Cinnamon edition.
[B01BZ30186.pdf](https://github.com/jingyu9575/multithreaded-download-manager/files/5834712/B01BZ30186.pdf)

**Comment by jingyu9575** [comment]
Did you use the *Download* button, or the *Continue in Browser*, *Open*, or *Save* buttons? I think the link can only be used once, so if you click the *Download* button, the extension cancels the request and re-add the task, and the server refuses to provide the file again.

**Comment by jingyu9575** [comment]
This type of servers are tricky; if you right-click this green button:

![图片](https://user-images.githubusercontent.com/8923139/105018087-84c85500-5a7f-11eb-9a9f-617982d216d4.png)

it can work, although only one thread is supported. Otherwise, in the auto-prompt dialog, choose the *Continue in Browser* button to pass it to the built-in download. Using the *Download* button in the dialog does not work because the link can only work once.
