### ISSUE TITLE
Network Error - download stalls.

### ISSUE THREAD

**Issue by doug123** [jingyu9575/multithreaded-download-manager#167]
Hi - I am getting network errors and have to keep hitting the play (arrow) button to continue.

Is there an option to force the continuation of the download, even with a network error?

Thanks.

**Comment by jingyu9575** [comment]
Does it help if the option *Maximum retries* in *Network* is cleared (set to *Unlimited*)?

**Comment by doug123** [comment]
Trying now - thank you!

**Comment by doug123** [comment]
That really helped - thank you.  It still dies on "Server error", but it's much less frequent.
