### ISSUE TITLE
Multithreaded downloads have a chance to become corrupted since updating to Firefox 102.0

### ISSUE THREAD

**Issue by Onurtag** [jingyu9575/multithreaded-download-manager#179]
Since updating to Firefox 102.0, zip files that I download have a chance to become corrupt.   
I could not see any errors in the built-in logs or in Firefox' extension debugging toolbox but I think [these changes](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/102) might be the cause of the regression.

The bug can be replicated by downloading a compressed zip file with multiple threads (4-6). 
The bug doesn't happen every time you download a zip file so you might have to repeat a few times.

Steps to replicate the bug (tested on a fresh profile):  
1. Find a medium sized (40MB+) zip file to test with. ([random example](https://github.com/yt-dlp/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl-shared.zip))  
2. Download the file with multiple threads (4-6).  
3. Open the zip file and use the test function of 7-Zip to see if there are any errors. Download the file again if there are no errors.  

---
**Update: The bug will be fixed with Firefox 104 release.**

**Comment by jingyu9575** [comment]
I tried 3 times with this file (4~6 threads) but there are no errors. I'll give more tries later.

**Comment by Onurtag** [comment]
Thanks for taking a quick look. 
I will also try to replicate it again on a different network and on another computer later today..

**Comment by Onurtag** [comment]
I think I have made some progress.  
Based on below points my guess is that there might be a problem with the file saving API on Firefox 102.0 on Windows.   

**Big find:**  
I tested the same link but this time I entered the file's correct sha256 checksum into the download popup so the addon could verify it.    
![image](https://user-images.githubusercontent.com/7430003/177049866-a07c496f-7ce4-4394-ba4f-8cb644198845.png)
The checksum validation seems to succeed but the downloaded file is still corrupt. This might mean that the corruption occurs while saving the file to the disk.  

**Other finds:**  
1. I was able to replicate the bug with a single download thread. Although it is a bit harder to replicate.  
2. I was able to replicate the bug on a completely different Windows 10 computer.  
3. I couldn't replicate the bug on a Linux Mint VM. (10 tests, although it might just be harder to replicate)  

I have also hex compared a successful download and a failed download. The broken files are usually missing 100KB - 700KB sized chunks on random locations (locations that would be in the middle of a download segment)

**Comment by thevladsoft** [comment]
I'm also seeing this behavior. It's a little random, as not always corrupt the same file the same way. As an example, after downloading the same video file several times, they will fail in different points, in some cases it will in the middle, others near the end and others it will be completely unwatchable.

As a possible hint, in one occasion, after it downloaded the file, it got stuck while recording to disk. I tried pausing and unpausing, and then it simple gave an error. Maybe firefox is deleting the pieces before de addon have had time to copy them to the final file? Some case of race condition?

**Comment by jingyu9575** [comment]
I've tried again for several times, but I still cannot reproduce the problem. None of my downloaded files are corrupted. This going to be difficult...

I just looked at the file saving code, but did not see anything abnormal. Maybe there is a bug in this Firefox version (I also meet some mysterious bug when upgrading Firefox recently, which is solved by manually deleting its storage directory).

**Comment by ricktoronto** [comment]
Also having this issue with 102ESR.  Some uploads are fine, others are corrupted.  The larger the download file, the more often it is corrupted.

**Comment by Onurtag** [comment]
It definitely works correctly when I test it on a portable Firefox 101.0.  

I am going to try using mozregression now.

**Comment by Onurtag** [comment]
I have finished bisecting using mozregression (tested with ~100 downloads on good builds, ~30-40 downloads on bad builds) and I have spotted the exact Firefox changeset that has caused the regression. [Result image](https://user-images.githubusercontent.com/7430003/177225481-089326ac-567e-47a0-856b-e5925e9ff318.png)      
The final result points to the following diff:  
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=69fb0f363c1889e054c8aac505a63875e6ce3099&tochange=3f4ebef6a4b1b4fb858d9d8eba17a4ccae268d1a  

I have also tested the latest nightly build.  
Although the addon on the latest nightly build gives me a "Cannot access internal storage" error, the addon still works and it is able to download files.  
But the file corruption bug was still there which means that it is not yet fixed.

**Comment by Onurtag** [comment]
I have narrowed down the cause of the bug to the `URL.createObjectURL()` function. (File background/multithreaded-task.js` line 449)   
Whenever the bug occurs, the createObjectURL function returns a blob URL which points to a file that is missing one or more blobs from the source file.  

The bug can be easily replicated with these steps: ![(video link)](https://user-images.githubusercontent.com/7430003/177475817-404b780a-89ee-468e-8547-fc55ef6bbe90.mp4)  
  
1. Inspect the addon (debugger) and put a breakpoint on file: `background/chunk-storage.js` line 215: `return new File(blobs, "file");`  
2. Download a medium sized (10MB+) file, use multiple threads to increase the number of blobs.   
3. Run the following snippet in the console when the breakpoint is hit.  
```javascript
//blobs = [blob1, blob2, ... , blob10, ...];
var theFile = new File(blobs, "file");

async function test() {
    for (let i = 0; i < 10; i++) {
        //Generate object URL (has a chance to generate a url with corrupt data)
        //corruption = missing one or more blobs from theFile above
        var theURL = URL.createObjectURL(theFile);
        //Download generated URL (works correctly, always downloads the same data)
        await browser.downloads.download({ url: theURL, filename: "Test_" + i, saveAs: false });
    }
}
test()
```

**Comment by jingyu9575** [comment]
Thank you very much for looking into this. I've tried these reproduction steps but the files seem to be not corrupted:

https://user-images.githubusercontent.com/8923139/177553203-a42ac3e7-b5b7-4bf2-be6d-cdacc0be09f9.mp4

**Comment by Onurtag** [comment]
I have also tried to reproduce the bug on a [seperate test extension](https://github.com/Onurtag/bad-object-url) but I couldn't reproduce it there.   

I think this is out of our hand now. It looks like a low level bug.  
Firefox devs need to take a look at this. Should I go ahead and create a bug on bugzilla?

**Comment by military1** [comment]
I'm here, too. The problem repeats itself on Linux Mint, Firefox 102.

**Comment by jingyu9575** [comment]
Today I've done another test in a virtual machine (Windows 10 x64), using the method in https://github.com/jingyu9575/multithreaded-download-manager/issues/179#issuecomment-1175821990 .

Finally I can reproduce it:

![图片](https://user-images.githubusercontent.com/8923139/178523800-50dac82f-6176-493b-86a0-47377634434b.png)

**Comment by ricktoronto** [comment]
To confirm, update to Firefox ESR 102.0.1 does not fix the corrupt file issue.

**Comment by DocSniper** [comment]
Same problem here with Firefox 102.0.1 on Arch Linux. However, not only ZIP files seem to be affected, the download of .img files was also affected several times for me.

**Comment by sbstn87** [comment]
The same problem happens with Firefox 102.0.1 on Windows. It affects mostly .exe installers downloaded from GitHub.

**Comment by Exa8yte** [comment]
I'm having the same issue, Firefox 102.0.1 (64-bit) Windows 10 Home 19043.1826

**Comment by Onurtag** [comment]
I have opened a bug on bugzilla so the Firefox devs can take a look at the bug. [Link](https://bugzilla.mozilla.org/show_bug.cgi?id=1780054) for those who are interested.  
(only comment there if you have something to add)

**Comment by Onurtag** [comment]
> i am not sure, is it possible that this bug may create only if `browser.downloads.download` use URL from `URL.createObjectURL`
@mix5003 I don't think the method of download matters. Once the URL is created you can also paste it on the browser window to download the file.  
When I did some tests on the addon the URL was giving the same corrupt file every single time no matter how I downloaded it.

**Comment by mix5003** [comment]
@Onurtag i think i can create [test extension](https://github.com/mix5003/bad-object-url). can you try it?
i think to replicate this bug it must use blob from indexedDB, URL.createObjectURL and download file from URL that just created.

pls review my code first, i not familiar with indexedDB, so i may do some thing wrong. if my code is correct you may put this in bugzilla. 

i leave URL that already create as a link. you can download corrupt file again in same link. but when js fetch for mD5 that link it seem work correctly.

**Comment by Onurtag** [comment]
@mix5003 Great work! I can confirm that the bug can be replicated using this test addon.  
The code looks good. I will make a comment on bugzilla with your test addon and your findings.

**Comment by jingyu9575** [comment]
Sorry for the delay.

It seems that the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1780054) has been fixed on Firefox 105. I just tested on Firefox Nightly (on the virtual machine that had the bug), and there is no prorblem now.

Thank you all very much.

**Comment by Onurtag** [comment]
I can also confirm that its fixed on Firefox 105. I will add that info to the op.

**Comment by mo-han** [comment]
so afterall this is just a firefox bug, and now it's working well again?

**Comment by Onurtag** [comment]
No, currently it is only fixed on the development version.
It will be fixed for most of the users when Firefox 105 releases in ~7 weeks. 
Here is the release calendar if you want to see the release dates: https://wiki.mozilla.org/Release_Management/Calendar

**Comment by jingyu9575** [comment]
@ricktoronto It seems that the bug is fixed on ESR 102.

**Comment by Onurtag** [comment]
Firefox 104 stable released yesterday and I can confirm that the bug is now fixed.  
I am closing the issue now. Thanks for the effort everyone!
