### ISSUE TITLE
how can i limit the max. simultaneous downloads?

### ISSUE THREAD

**Issue by airen27** [jingyu9575/multithreaded-download-manager#191]
edit: nevermind, found the option

hey, great tool.
i couldn't figure out how to limit how many downloads run at a time.
i have around a hundred 1Gb files and i dont want to download them all at the same time.
thanks for your help!

**Comment by airen27** [comment]
sorry, completly overlooked the option.

**Comment by vassilyzaitsev** [comment]
Wow! That's not easy to find. I thought something like that would be in the network page 😅😅

If anyone else is looking: 

![03-02-2023 - 18h23m00s (4868)](https://user-images.githubusercontent.com/35409978/222557435-685f2383-c43f-4e15-b755-1c22f401ee98.png)
