### ISSUE TITLE
All permissions necessary?

### ISSUE THREAD

**Issue by edjw** [jingyu9575/multithreaded-download-manager#23]
![screen shot 2018-04-19 at 16 53 25](https://user-images.githubusercontent.com/6547979/39003228-52ef2a78-43f2-11e8-8c20-13c3536f551d.png)

The permissions required to install this is quite long and it's not clear what they are for.

Could you consider removing unused permissions or explaining on the Mozilla Add-ons page what the various permissions are used for?

**Comment by jingyu9575** [comment]
They are necessary for the extension's functions.

I have created a wiki page to explain them: [Privacy and Permissions](https://github.com/jingyu9575/multithreaded-download-manager/wiki/Privacy-and-Permissions). This link is added to the Mozilla Add-ons page.
