### ISSUE TITLE
Dialog not closing causes multiple downloads to start

### ISSUE THREAD

**Issue by rayman89** [jingyu9575/multithreaded-download-manager#25]
On firefox 61 in windows 7 when the download has not started and says "Preallocating" the dialog for multithread addon to start it does not close and if you click on download multiple times multiple downloads get added to the list.

**Comment by jingyu9575** [comment]
This is the same issue as #24 (in Chinese) and has been [fixed in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1457673). Please update Firefox.
