### ISSUE TITLE
Remember window size/position

### ISSUE THREAD

**Issue by rayman89** [jingyu9575/multithreaded-download-manager#3]
I noticed that the window that appears when  a download is going to start is quite big and resizing it does nothing because the next time it appears it appears in the same big size. Also the appear in the center thing seems to center the window based on the top left corner and not based on the center of the opened window. Could you add an option to remember the position/size of window or at least have an option to show a small window. Like this big for example

![imagen](https://user-images.githubusercontent.com/5449042/33728180-889b3714-db71-11e7-8aaa-4bebd3c6ed64.png)

**Comment by jingyu9575** [comment]
An option to remember will be added. I'd also like to know whether the current centering has problems. This is what I get on Firefox 57/Windows 10. Is it different on your system?
![screenshot](https://user-images.githubusercontent.com/8923139/33763199-86cf3776-dc4a-11e7-9471-15328cb952b9.png)

**Comment by rayman89** [comment]
Yes I use a maximized window and the window size for the downloader is huge and centered based on the top left corner

![image](https://user-images.githubusercontent.com/5449042/33771205-d2cb3cba-dbf5-11e7-9c96-bb98c26fb982.png)

**Comment by jingyu9575** [comment]
In the screenshot, the window size is incorrect but the window position is expected. The green box is where the extension try to place the window.
It is found that `privacy.resistFingerprinting` can cause this problem. Firefox sets every window's size to be a common value in this mode, so both the main windows and the extension windows may have unexpected size. The extension now workarounds it by resizing the window afterwards.
Options to remember window size/position are also added.
![screenshot](https://user-images.githubusercontent.com/8923139/33793522-d9fa94d2-dcf3-11e7-9ede-c293e0cebc0e.png)

**Comment by rayman89** [comment]
That setting seems to break more things than it helps. Thank you for the info and changes.
