### ISSUE TITLE
Addon aborts download

### ISSUE THREAD

**Issue by iPooPaLot** [jingyu9575/multithreaded-download-manager#30]
The addon aborts a download and the red "X" shows the message "r is null"

**Comment by jingyu9575** [comment]
I have also seen this error several times, but has not found the reason yet. I'll look into it.

**Comment by jingyu9575** [comment]
It is found that when the network is interrupted, this extension sometimes gets 0 bytes and tries to write zero-sized data, which is invalid, with a confusing error message "r is null".

Now the extension detects such cases and treats them as recoverable network interruption. 

If you frequently see this error before, your network may be unstable. Increasing the "maximum retries" option may help (in the new version).
