### ISSUE TITLE
Adding download scheduler tweak

### ISSUE THREAD

**Issue by xerta555** [jingyu9575/multithreaded-download-manager#31]
Hello,

It could be possible to add an scheduler tweak in your WE please ?
Because it lazy to waiting the end a download to launch the next one, because some hosters don't allow to download several files on their servers simultaneously.

The second reason is that on ADSL connexions, sometimes, due to the fact that there is loss on this type of Internet line, when several downloads are launched at the same time, the download speeds don't necessarily occupy all the bandwidth. 
As a result, the total time of all downloads is extended.

Thanks you in advance :)

**Comment by jingyu9575** [comment]
An option "simultaneous download tasks" has been added.

On these servers, you may also want to set the option "Threads" to 1.

![default](https://user-images.githubusercontent.com/8923139/42275457-ec19ff00-7fc2-11e8-8c85-05e7665343aa.png)
