### ISSUE TITLE
[Out of subject] Need help with Javascript

### ISSUE THREAD

**Issue by xerta555** [jingyu9575/multithreaded-download-manager#35]
Hello,

As i don't know how to contact you, i open an issue here.

Maybe that you could help me by tell me how i could make a timer loop running every 3 hours a JS code, all this directly in a file named background.js explicitly declared as a background JS file in my `json` manifest.

There is the actual state of my background.js:
[background.zip](https://github.com/jingyu9575/multithreaded-download-manager/files/2217197/background.zip)

#### U will seea first part from:
`function startTimer(duration, display) {`
#### to:
`	}, -1);`
`}`

#### And the second part from:
`var parents = document.getElementsByClassName("itemcontent");`
#### to:
`        done = true;`    
`  }`
`}`

Thank you in advance for your help :)

**Comment by xerta555** [comment]
After some investigations, there is my new background.js file:
[background.zip](https://github.com/jingyu9575/multithreaded-download-manager/files/2217246/background.zip)

I wan to specify the saving path in my script, for now its setup like that:
`imgs.setAttribute("/walls/", "Image1.jpeg");`

I don't know if it's the right way, can u confirm it to me or do u have a better one ?

**Comment by jingyu9575** [comment]
Yes `setInterval(functionName, 3 * 60 * 60 * 1000)` is the way to make the timer. 

I am not sure what you are trying to do with this `setAttribute` call. The DOM function [`setAttribute`](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) changes an [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) of an element. See the [example](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute#Example): the button is an element, which has an attribute called `"disabled"`. The statement `b.setAttribute("disabled", "")` changes this attribute to an empty string, causing the button to be disabled. There is no known attribute called `"/walls/"`, so your statement has no effect other than storing the value.

There are some other errors in the file, and I think it does not work in the browser yet.

Are you trying to download the first 3 photos on http://feed.500px.com/500px-best , and set the download paths to "/walls/ImageN.jpeg"?

---

My email address is: qw2g64!zoho:eu (`!` is `@` and `:` is `.`, to hide from spam bots).

**Comment by xerta555** [comment]
> Yes setInterval(functionName, 3 * 60 * 60 * 1000) is the way to make the timer.

Ok noted.

> I am not sure what you are trying to do with this setAttribute call. The DOM function setAttribute changes an attribute of an element.

I just have upload my WE on my git: [https://github.com/xerta555/500pxOnNewTab](https://github.com/xerta555/500pxOnNewTab)
With the `setAttribute` call, i try to defining some properties (i take that from stackoverflow and adaptate it for my idea. (the saving path for the walls from 500px, saved as the filename `ImageN.jpeg`).

> The statement `b.setAttribute("disabled", "")` changes this attribute to an empty string, causing the button to be disabled.

Understand.

> There is no known attribute called `"/walls/"`, so your statement has no effect other than storing the value (Edit: it has error because / is not allowed in attribute names).

Yesterday i removed the slashs on `"/walls/"` :+1: 

> Are you trying to download the first 3 photos on http://feed.500px.com/500px-best , and set the download paths to "/walls/ImageN.jpeg"?

Yeah, to be bref, there is what i want that my WE addon for FF make:
-> In background, the WE check if there are already one or more wallpapers in the `walls` folder, if yes rename them to avoid any conflits with next steps (renaming them with higher numbers), download every 3 hours the 3 thirst wallpapers from the 500px URL (http://feed.500px.com/500px-best) in the `walls` folder of the addon, and apply the first one to the background of the internal NewTab page of Firefox.

The first option that i would like to add is the choosing if the wallpaper is scape, scalled in the background of the NewTab page.

We can continue to speack on my repo in the Issues tab to avoid spamming your one about subject out :)
Thank you very much for your help.
(I would be so happy if i could use shell code in my WE and not js lol..)

**Comment by jingyu9575** [comment]
(This discussion is continued at OP's repo.)
