### ISSUE TITLE
界面选择 Dark 模式时图标还是黑色的看不太清

### ISSUE THREAD

**Issue by weijarz** [jingyu9575/multithreaded-download-manager#38]
使用Firefox内建的Dark主题时图标颜色黑色在深灰底上看不清

**Comment by jingyu9575** [comment]
是这个工具栏图标吗？亮暗色可以在选项中选择。
![default](https://user-images.githubusercontent.com/8923139/44128638-a253d5f6-a076-11e8-95c0-8147c74266ae.png)
![default](https://user-images.githubusercontent.com/8923139/44128741-2102ee0a-a077-11e8-9e9e-d6482870a6f6.png)

在 Firefox 61.0.2/Windows 10 下测试，即使选择了深邃主题，扩展弹出界面的背景色仍然是亮色的，里面的图标不会出现问题。

**Comment by weijarz** [comment]
@jingyu9575 不好意思没看到选项，我以为是会自动切换的。

![screenshot from 2018-08-15 11-13-49](https://user-images.githubusercontent.com/8944061/44129711-559fa8ec-a07c-11e8-9a98-8c1c63c7dd16.png)
