### ISSUE TITLE
Corrupted downloads if multithreaded (site/code specific?)

### ISSUE THREAD

**Issue by Harryons** [jingyu9575/multithreaded-download-manager#46]
I use your addon and globally I'm happy with it. 
I like it because its lightweight (without unsollicited connections crap) and practical enough.
Thanks for your work!

However I would like to signal a buggy behavior upon certain downloads that are corrupted.

Try to download from these links, both exe and/of zip files.
Using your addon (MTDM), then using browser builtin FF download function.
https://www.novirusthanks.org/products/syshardener/
https://www.novirusthanks.org/products/exe-radar-pro/
https://www.novirusthanks.org/products/osarmor/

You will most certainly find differences like I did.
For example the "Os armor" link, in osarmor_setup.exe file: starting from hex offset 3fe930
For example in syshardener_setup.exe file: starting from hex offset 17fde8
For example in syshardener_portable.zip file: starting from hex offset 16fdeb

Lets investigate this latter case "syshardener_portable.zip" :
At : https://www.novirusthanks.org/products/syshardener/

It looks like it is aleatory as MD5 hash gives :
f53004d33e41a21e56bfd065e42eff5c *syshardener_portable(2).zip ----> corrupted, downloaded by MTDM / session 1
d5d747518232c4a2eb815295643b8c7a *syshardener_portable(1).zip ----> corrupted, downloaded by MTDM / session 2 (browser restarted!)
db582ec7f3c7ade355a2979fed6dc10f *syshardener_portable.zip -------> this is ok, downloaded by the browser (builtin)

You see the corruption looks aleatory : 
the data corrupted is different but it always starts from the same offset 16fdeb. 
(well, its : 177de8 if troubleshooting options checked in configuration general tab)
Allways compared to the correct file!

It seems it happens only on some websites (here: novirusthanks.org) and only for files above some Mb (4-5).
Smaller files are ok.

The same files taken as example: the data mismatch in the wrong file that starts at 16fdeb,
is actually the (good) data starting at 073078 in the good file.

Bingo! : I made a try with 1 only thread and it downloaded it correctly. Lets try with 2 threads!
Now, error starts from the 2nd thread (offset 2dfde8). Same with "minimal chunk" 2048 (instead of 1024 by default) the offset is then 2e3de8.

There must be a sync problem between download threads...
I discovered this problem on this site: https://www.novirusthanks.org
other downloads I made might have been corrupted... I don't know, but I didn't realize this. I downloaded a lot, opened those files without a problem.
I really think this bug is server-code specific...

Hope this can help you to get on the right path to work it out.
Cheers!

My Environment:
FFQuantum 61.0.2 32bit (Not tuned). MTDM default settings.
OS: 32bit Win7 pro sp1.

**Comment by jingyu9575** [comment]
> I really think this bug is server-code specific...

I agree. I inspected this site with developer tools and found the server's handling of multithreading is incorrect. 

The site says it has multithreading support, but when the extension asks for a part with an offset, the site provides the entire file (without offset) instead, so the extension reads the first part again. Therefore, an incorrect file is downloaded, which is just the first part repeated. 

The correct behavior for servers is either providing the correct part when asked, or outright denying multithreading support (causing the extension to fallback to a single thread). Most servers follow one of them, so I think most of your other downloads are not affected.

---

It seems possible to detect such incorrect behavior by checking the response status (full file / partial). As the extension's code is under massive restructuring for 2.0, I will need some time for this feature.

**Comment by Harryons** [comment]
Thank you so much for the clarification.
Your addon is the cleanest and super lightweight. I love it.
Excellent is also the choice given to use builtin browser function instead...
If you could add link detection (regex filtered) function for "automatic" link selection (as had DTA), it would be great.
In your description, make a huge accent to the fact that you don't gather and dont send any stats.
This is a great "selling" arg, people like this.
Just go for it, and you will replace DTA soon!

**Comment by jingyu9575** [comment]
> add link detection

Planned for v2.0.

> In your description...

Maybe after 2.0 I need to rewrite the description with the features and highlight the privacy statement. (I'm not good at writing or promoting though.)

I'd say it is unfortunate that add-on developers even need to mention no-tracking now. Before the recent change in the add-on site's moderation, I think most extensions there did not track the user, and it was very safe to install and test a new extension.

**Comment by chenshaoju** [comment]
Firefox Version: 67.0.4

此问题同样发生在 1.9.5.3 版本中。
This issue is the same happened in 1.9.5.3 version.

当我尝试从 https://ftp.mozilla.org/pub/firefox/releases/67.0.4/win64/en-US/ 下载时，每次下回来的文件大小不一样，解压均提示被破坏。
When I try to download firefox from https://ftp.mozilla.org/pub/firefox/releases/67.0.4/win64/en-US/  , every time the file size is different. When I install, The file is corrupted.
![image](https://user-images.githubusercontent.com/515763/59960218-a950f980-94f7-11e9-9898-c0c612f80e85.png)

但是，我可以使用第三方的下载软件，如FlashGet来顺利多点下载。
But, I can use 3rd-party download tools to download successfully.

**Comment by jingyu9575** [comment]
@chenshaoju I don't think it is the same problem. Let's continue in #62.

**Comment by jingyu9575** [comment]
> buggy behavior upon certain downloads that are corrupted

The upcoming version v2 will try to detect such malformed response and show an error. It is still under testing. The unsigned extension XPI can be found in [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases).

![图片](https://user-images.githubusercontent.com/8923139/62003251-e3d93200-b146-11e9-8eae-040dc01e90c1.png)

> add link detection

Available in v2.

![图片](https://user-images.githubusercontent.com/8923139/62003287-88f40a80-b147-11e9-90bc-73730f1db226.png)
