### ISSUE TITLE
火狐63没有无法访问内部储存。

### ISSUE THREAD

**Issue by 1608637229** [jingyu9575/multithreaded-download-manager#47]
隐私安全我基本都是默认设置的。不知道问题出在哪

**Comment by jingyu9575** [comment]
在我这里没有发现问题，火狐63 / Windows 10。

请打开 about:debugging，选中“启用附加组件调试”，然后单击这个扩展的“调试”按钮（允许连接），切换到“控制台”标签。

1. 单击左上角垃圾桶图标清除日志，然后禁用再启用这个扩展。是否有错误信息？
2. 运行 `initialization.then(console.log, console.error)` ，输出是什么？

**Comment by 1608637229** [comment]
错误信息：
HTML 文档使用 meta 标签声明了一个不支持的字符编码。该声明被忽略。               background.html:4
传递给 indexedDB.open 的选项中所用的“storage”属性已不赞成使用，很快将被移除。要获得持久存储，请使用 navigator.storage.persist() 代替。                                                                   common.js:270:24
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code.
运行后的输出：
Promise { "pending" }
​
<state>: "pending"
​
<prototype>: PromiseProto { … }

DOMException: "The operation failed for reasons unrelated to the database itself and not covered by any other error code."

**Comment by jingyu9575** [comment]
错误信息显示，火狐打开内部存储时出现未知错误。可能是火狐的配置文件损坏。

[相关问题（英文）](https://stackoverflow.com/q/32540859)

建议尝试：

1. 移除、重装这个扩展；
2. 删除扩展的存储数据。在 about:support 中打开配置文件夹，扩展存储数据在 storage/default/moz-extension+++<扩展UUID> 和 storage/permanent/moz-extension+++<扩展UUID> 中。扩展UUID可在 about:debugging 中的“内部 UUID”找到。
3. 如果实在没有办法，[刷新配置文件](https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings)很可能会解决这个问题（注意备份数据、设置和扩展）。

**Comment by 1608637229** [comment]
刷新配置文件后恢复正常了。我也不知道为什么会出现这个问题。
