### ISSUE TITLE
Is it possible to make use Storage Access API?

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [jingyu9575/multithreaded-download-manager#48]
See: https://developer.mozilla.org/docs/Web/API/Storage_Access_API

**Comment by jingyu9575** [comment]
I don't think so.

> The Storage Access API provides a way for embedded, cross-origin content to gain unrestricted access to storage that it would normally only have access to in a first-party context (we refer to this as an origin’s first-party storage).

It is a way for sites to request exceptions from restrictions such as tracking protection. 

You may be looking for the [Writable Files](https://wicg.github.io/writable-files/) proposal. It is still at an early stage and not supported by browsers.
