### ISSUE TITLE
Feature Request: Open folder, and, date/time

### ISSUE THREAD

**Issue by xDebuggerx** [jingyu9575/multithreaded-download-manager#51]
Hi,

Feature request:

1. A Menu Option (enable/disable) to open the folder where the file(s) were downloaded upon the download completing/finishing

2. Showing the Date/Time of the downloaded file(s) next to or below the file name (similar to how Firefox does it)

Thank you!

**Comment by jingyu9575** [comment]
These features are added in the upcoming verison v2, which is still under testing. The unsigned extension XPI can be found in [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases).

![图片](https://user-images.githubusercontent.com/8923139/62007632-87940380-b182-11e9-9ed2-ec856f2b9d0d.png)
