### ISSUE TITLE
请问主进程外扩展 这个在哪开启啊？ 另外火狐内部储存是哪里， cache目录？

### ISSUE THREAD

**Issue by biluohc** [jingyu9575/multithreaded-download-manager#6]
我的弹出窗口弹出窗口都是空白的（Linux Fx57）

**Comment by jingyu9575** [comment]
> 主进程外扩展

打开about:config，设extensions.webextensions.remote为true。这个选项在Linux下没有自动开启，因为有扩展面板周围黑框的问题。目前我在用 userChrome.css 隐藏黑框。[了解更多](https://github.com/jingyu9575/multithreaded-download-manager/wiki/Problems-with-disabling-the-feature-%22out-of-process-extensions%22#zh-cn)

> 火狐内部储存

指IndexedDB，文件保存在~/.mozilla/firefox/***/storage/permanent/moz-extension+++***/idb/***.files/ 。可以右击扩展图标，在新标签页中打开，F12→存储→Indexed DB中查看存储信息。
