### ISSUE TITLE
Corrupted downloads on ftp.mozilla.org

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/multithreaded-download-manager#62]
> Firefox Version: 67.0.4
>
> 此问题同样发生在 1.9.5.3 版本中。
> This issue is the same happened in 1.9.5.3 version.
>
> 当我尝试从 ftp.mozilla.org/pub/firefox/releases/67.0.4/win64/en-US 下载时，每次下回来的文件大小不一样，解压均提示被破坏。
> When I try to download firefox from ftp.mozilla.org/pub/firefox/releases/67.0.4/win64/en-US , every time the file size is different. When I install, The file is corrupted.
>
> 但是，我可以使用第三方的下载软件，如FlashGet来顺利多点下载。
> But, I can use 3rd-party download tools to download successfully.

@chenshaoju 这和 #46 应该不是同一个问题。https://ftp.mozilla.org 网站的多线程支持是正常的。在我这里也没有发现损坏的问题，文件大小始终是44.8MB。

请检查下载过程中文件大小是否正确。

![图片](https://user-images.githubusercontent.com/8923139/59972087-4759c800-95bb-11e9-89cf-ec749e23f075.png)

另外，如果在新标签页中按F12打开开发者工具，选择网络标签，然后直接在地址栏中打开 https://ftp.mozilla.org/pub/firefox/releases/67.0.4/win64/en-US/Firefox%20Setup%2067.0.4.exe ，切换到内置下载后取消，返回的 Content-Length 是否正确？

![图片](https://user-images.githubusercontent.com/8923139/59972106-b6cfb780-95bb-11e9-8248-4b869165813d.png)

**Comment by chenshaoju** [comment]
Firefox自带的下载下回来的是好的，文件长度一致。
![image](https://user-images.githubusercontent.com/515763/59972300-45920380-95bf-11e9-983d-11cc6b28800c.png)

但是用MDM下载回来的大小就不一样：
![image](https://user-images.githubusercontent.com/515763/59972317-93a70700-95bf-11e9-959b-afaf0848d002.png)

我找了另一个多线程下载器（Turbo Download Manager (v2) https://addons.mozilla.org/firefox/addon/turbo-download-manager/ ）也下载了三次，没有问题：
![image](https://user-images.githubusercontent.com/515763/59972358-25af0f80-95c0-11e9-8ccf-d9e5864968db.png)

我怀疑是不是断点续传的部分有问题？

**Comment by jingyu9575** [comment]
下载完成之前也显示不同的长度吗？

**Comment by chenshaoju** [comment]
这个窗口不能一直打开，有点难度…… 
![demo](https://user-images.githubusercontent.com/515763/59972437-d538b180-95c1-11e9-9504-17b0ba9eed81.gif)

**Comment by jingyu9575** [comment]
这就非常奇怪了，下载开始时文件的大小就是从 Content-Length 取得的。之前我也没遇到过类似的情况。
我再检查一下。

**Comment by jingyu9575** [comment]
下一个版本 v2 会检查各线程文件大小是否匹配，也许能发现问题的原因。v2 目前正在测试阶段，可以到 [Releases](https://github.com/jingyu9575/multithreaded-download-manager/releases) 下载未签名的扩展 XPI。

**Comment by chenshaoju** [comment]
感谢。

**Comment by jingyu9575** [comment]
普通版的 Firefox 只能临时安装，在 about:debugging#addons 中临时载入，重启后会还原。

---

如果愿意测试，请在扩展选项 - 高级页面将日志级别调整为“信息”，这样下载日志里可以看到扩展接收到的文件大小。多谢！

![图片](https://user-images.githubusercontent.com/8923139/62015661-2438be80-b1e0-11e9-8ed4-88b6da385060.png)


![图片](https://user-images.githubusercontent.com/8923139/62015638-fc495b00-b1df-11e9-9269-decf9157fb64.png)

**Comment by chenshaoju** [comment]
感谢，目前看起来一切正常了！

![GIF](https://user-images.githubusercontent.com/515763/62016704-3584c980-b1e6-11e9-8abb-ca58ea090197.gif)
