### ISSUE TITLE
Firefox 67 compatibility with e10s disabled

### ISSUE THREAD

**Issue by mrochaaa** [jingyu9575/multithreaded-download-manager#66]
I'm need use Firefox with multi process disabled because I have low memory, then have an bug, with e10s disabled the new download window (extension window) have just an white background and any content. Firefox 67.0.4

**Comment by jingyu9575** [comment]
If you are using v1, see if the option "Fix the problem with blank extension windows" helps. 

Unfortunately, the compatibility options are not included in the upcoming v2, since it only supports Firefox 68+ and e10s cannot be disabled on Firefox 68+.

**Comment by mrochaaa** [comment]
thanks, really this option fixed the problem, then I can't install v2 in my 67? , if possible keep this option, so I and others can continue use in 67

**Comment by jingyu9575** [comment]
> keep this option

This will require lowering the minimal version to be 67, which needs time for testing. 

In addition to this one, there is another compatibility option "The first saving attempt was problematic and should be skipped" that must be ported.

**Comment by mrochaaa** [comment]
ok, thanks so much

**Comment by jingyu9575** [comment]
Firefox 67 is now supported with 3 workarounds. Unlike v1, there are no options and disabling e10s will automatically enable the workarounds.

**Comment by mrochaaa** [comment]
very good
