### ISSUE TITLE
Feature to open download list in an tab

### ISSUE THREAD

**Issue by mrochaaa** [jingyu9575/multithreaded-download-manager#67]
Suggestion:

Title said all, an setting, if you click the plugin icon, instead of popup, open in an tab

**Comment by jingyu9575** [comment]
It is in the right-click menu:

![图片](https://user-images.githubusercontent.com/8923139/62001850-22152800-b12c-11e9-8150-2e8d5e722cbb.png)

**Comment by mrochaaa** [comment]
thank you

**Comment by jingyu9575** [comment]
Added in v2.

![图片](https://user-images.githubusercontent.com/8923139/62100546-bfa35f80-b2c4-11e9-9285-5deca5479baa.png)
