### ISSUE TITLE
下载大文件时,某些时候无法暂停也无法删除

### ISSUE THREAD

**Issue by Remonli** [jingyu9575/multithreaded-download-manager#7]
点击扩展图标弹出的控制面板完全不可控,该情况出现时,下载的文件尺寸有数G的,也有200多M的.

环境: fx 58 beta 最新, win10 1709

**Comment by jingyu9575** [comment]
已知问题，Windows下文件需要预分配空间，此期间无法操作。文件越大/磁盘速度越满，问题越严重。
这需要一些时间修改（我在国外，时间较紧张）。

**Comment by jingyu9575** [comment]
v1.0a1 版本尝试修复了这个问题。现在扩展会明确显示预分配空间的状态，预分配时可以暂停/删除。
