### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by ghost** [jingyu9575/multithreaded-download-manager#73]
1 - Add multi selection in download list, to pause/play many items together using shift + click

2 - context menu item to force re-download (restart)

3 - option to add links "paused" to download after

4 - an button in toolbar to clear the download list manualy

**Comment by mrochaaa** [comment]
If you actually implement this multi selection on the dl list, you can add the batch actions like, delete, play, pause, export select links as txt file, etc, can be very good. One other suggestion show the download progress in taskbar like the native dm is possible? Or the "chrome" API dont have this too? :) Also show the progress "%" of active downloads in tooltip, I know can't be in real time, but can be fine anyway as optional settings. What you think about?

**Comment by mrochaaa** [comment]
thanks you

**Comment by jingyu9575** [comment]
2 and 4 are done.

The difficuly of 1 and 3 is UI design.

1. the tasks cannot be selected now, and I think it is better to keep it this way by default and add a button to activate selection. Then it is a question where to put the bulk pause/resume/export actions.

3. The auto-prompt window already has 5 buttons, and adding more buttons will make it more confusing. Maybe a button inside a drop arrow is better?

---

> download progress in taskbar

I don't think it is possible. There is no API, and the only way I can think of is to download a website file with the builtin manager, and then coordinate with the site to control the displayed progress. It will have privacy issue that I'd avoid. 

Firefox 70 is going to have the libdweb-protocol API which may help, but I haven't tested it yet.

---

> show the progress "%" of active downloads

I will need to find what this % value means: whether it is percentage of file size, or estimated time left. When there is multiple downloads with different speed, the estimation can be inaccurate. Maybe it is better to see what other download managers do.

**Comment by mrochaaa** [comment]
All right! 

> a question where to put the bulk pause/resume/export actions

I think multi-selection by default is ideal like all managers is ever, but, what you think about put "Add new download and Options" buttons to the center or right side of the "controls bar" and put an new button in the left side to enable multi selection?

> auto-prompt window already has 5 buttons, and adding more buttons will make it more confusing

If you add an new button called "Add Paused" between Download and Cancel buttons? Maybe you can even change "download" to "Download Now"?

> I will need to find what this % value means

I think so, show the last 10 or 5 files of the download list in tooltip like:

best porn videos ever.zip | 34% | 1:32:12

job files.7zip | 100%

my new app.exe | 80% | 10:12

the % shall be the "downloaded", the time, is time left, but I think the ideal is an setting to enable this "tooltip" feature only who want it.

**Comment by jingyu9575** [comment]
> show the last 10 or 5 files of the download list in tooltip

An option is added.

> add an new button called "Add Paused" between Download and Cancel buttons

![image](https://user-images.githubusercontent.com/8923139/64194476-ce77c600-ceb1-11e9-85be-533110e2c489.png)

An option is added. If you do not mind these 6 buttons, you can enable it.

> multi-selection by default is ideal like all external dl managers

I'll think about it. It needs some time, because maintaining the selection UI and dealing with keyboard navigations need work.

**Comment by mrochaaa** [comment]
Very good! Thanks so much! :)
