### ISSUE TITLE
Timeout Error while downloading

### ISSUE THREAD

**Issue by Katze0815** [jingyu9575/multithreaded-download-manager#74]
Hi,

since last update on 05. August I have massive issues with Download Manager.

Before this update, DM running very well for month without problems.

Now I get every 3-10 sec an Timeout and the download stopped. When I restart download, the download goes with full speed for the next seconds.

Where can I found the "old" version, bevor last update?

Kind Regards,
Peter

**Comment by jingyu9575** [comment]
The timeout can be disabled by removing the values in extension option - network. 

The old versions are in https://addons.mozilla.org/firefox/addon/multithreaded-download-manager/versions/ , and you'll need to disable auto-update for it.

**Comment by jingyu9575** [comment]
The default timeout should be 30 seconds. Are you seeing timeouts after a shorter time?

**Comment by Katze0815** [comment]
HI,

 

yes, I get Timeouts after 3 to 10 sec.

 

Before update on 05. August 2019, all was working very well.

 

 

Regards,

Peter

The default timeout should be 30 seconds. Are you seeing timeouts after a shorter time?

**Comment by Katze0815** [comment]
Thank you, I try it!

 

 

The timeout can be disabled by removing the values in extension option - network.

The old versions are in https://addons.mozilla.org/firefox/addon/multithreaded-download-manager/versions/ , and you'll need to disable auto-update for it.

**Comment by Katze0815** [comment]
… I installed the old version and all is running very well, so as ever. No timeouts, maximum speed downloading.

 

Regards,

Peter

 

The timeout can be disabled by removing the values in extension option - network.

The old versions are in https://addons.mozilla.org/firefox/addon/multithreaded-download-manager/versions/ , and you'll need to disable auto-update for it.
