### ISSUE TITLE
特殊网站文件名错误

### ISSUE THREAD

**Issue by ivysrono** [jingyu9575/multithreaded-download-manager#75]
http://ezandroid.cn/2019/08/10/ah-q-go-lite-1-3-0-has-been-released/
最下方
http://aqgo.ezandroid.cn/AQGoLite_1.3.0_GooglePlay_2019-08-10.apk
Firefox的内置下载没问题
扩展会把文件名识别成：
`utf-8'`

**Comment by jingyu9575** [comment]
这个网站应该是不符合标准的。已添加这一特殊情况的处理。
