### ISSUE TITLE
Small files do not show Green complete bar when done

### ISSUE THREAD

**Issue by robertheadley** [jingyu9575/multithreaded-download-manager#76]
![image](https://user-images.githubusercontent.com/1780455/63068517-01ddbb00-bed9-11e9-8ace-dc73a7dcf185.png)

This behavior makes a list of completed files look satisfying than it should. If there is a checkmark showing that the file is complete, the bar should automatically be completed.

I believe this is happening if files complete before a second segment could begin. 

Great extension. I love it. Thank you.

**Comment by jingyu9575** [comment]
I think it is because the server does not report the file size, so no progress can be calculated. GitHub's source download has this issue.

It can be fixed by setting the progress to 100% on completed though.

**Comment by robertheadley** [comment]
I do understand that, but I think that when the file is finished downloading, it should automatically complete the download at 100% and fill the green bar. A user experience enhancement.
