### ISSUE TITLE
There is no download tak

### ISSUE THREAD

**Issue by ToBos** [jingyu9575/multithreaded-download-manager#78]
I use Windows 10 64Bit 1903, Firefox 64Bit 68.0.2 and your addon 2.0b3
The new version cannot see anymore ongoing downloads of Firefox internal downloadmanager. In the past this was a very fine option to start the addon for those downloads only, when the internal manager results in a very low download speed.
Until this behaviour is fixed: To which version should I go back for the moment?

**Comment by jingyu9575** [comment]
Are you looking for this dialog? It has been merged into the first button "create new task".
![dialog](https://user-images.githubusercontent.com/8923139/63364746-c5aecc80-c3a8-11e9-9d56-6f2c7b614f11.png)

---

The new feature update is v2.0, so if you insist you can go back to 1.9.x.

**Comment by jingyu9575** [comment]
The next version will reintroduce the toolbar button (the icon has been changed).

**Comment by ToBos** [comment]
“Convert” works fine! Thank you for the information. 
 
Von: jingyu9575 <notifications@github.com> 
Gesendet: Dienstag, 20. August 2019 18:17
An: jingyu9575/multithreaded-download-manager <multithreaded-download-manager@noreply.github.com>
Cc: ToBos <tobias@bossert-inet.de>; Author <author@noreply.github.com>
Betreff: Re: [jingyu9575/multithreaded-download-manager] There is no download tak (#78)
 
Are you looking for this dialog? It has been merged into the first button "create new task".
 <https://user-images.githubusercontent.com/8923139/63364746-c5aecc80-c3a8-11e9-9d56-6f2c7b614f11.png> 
  _____  

The new feature update is v2.0, so if you insist you can go back to 1.9.x.
