### ISSUE TITLE
How do you create an exception to make this work with the "Always use private browsing" mode?

### ISSUE THREAD

**Issue by gojpdchx** [jingyu9575/multithreaded-download-manager#8]
I have the "Always use private browsing" option turned on. I noticed that the addon will not work, displaying an error message `Cannot access internal storage`.

`README.md`:
> The extension requires access to the internal storage (indexedDB) and does not work with the "always private browsing" mode without granting exceptions

Could you please tell me how to create an exception?

**Comment by jingyu9575** [comment]
I have written [this wiki page](https://github.com/jingyu9575/multithreaded-download-manager/wiki/About-%22Cannot-access-internal-storage%22) as the reply.
