### ISSUE TITLE
我发现 downthemall的 webextension 版可以直接下载到下载目录耶

### ISSUE THREAD

**Issue by hosxy** [jingyu9575/multithreaded-download-manager#81]
我发现 downthemall (webextension版) 可以直接将文件下载到 FireFox 设置的下载文件夹，不需要先把文件下到扩展的内部储存。如图：
![批注 2019-08-24 182651](https://user-images.githubusercontent.com/17108640/63636053-c42d1f00-c69c-11e9-85de-46f9848640b9.png)

**Comment by jingyu9575** [comment]
这个版本的 DownThemAll 使用浏览器自带下载功能来下载文件，不支持多线程。参见作者的[说明](https://github.com/downthemall/downthemall#about)以及[无法实现的功能](https://github.com/downthemall/downthemall/blob/master/TODO.md#p4)。
