### ISSUE TITLE
Failure to download from LibreOffice site !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#84]
Hi. I detected that your extension fail completely to download from download page of:
www.libreoffice.org

windows & .deb & .rpm packages are cached by extension but it failed at once show "server error" message !

Please, kindly, to check this ...

**Comment by jingyu9575** [comment]
Works here. What's the URL? Please click the 🔗 button and paste here. 

![图片](https://user-images.githubusercontent.com/8923139/64648340-47949180-d44d-11e9-8fa6-e72ccab68f6b.png)

**Comment by Nokia808** [comment]
They are here bellow:

https://mirror.library.ucy.ac.cy/tdf/libreoffice/stable/6.3.1/rpm/x86_64/LibreOffice_6.3.1_Linux_x86-64_rpm.tar.gz

https://mirror.library.ucy.ac.cy/tdf/libreoffice/stable/6.3.1/deb/x86_64/LibreOffice_6.3.1_Linux_x86-64_deb.tar.gz

https://mirror.library.ucy.ac.cy/tdf/libreoffice/stable/6.3.1/win/x86_64/LibreOffice_6.3.1_Win_x64.msi

& bellow the screenshots:

![screenshot-1](https://user-images.githubusercontent.com/25375330/64652971-ae498900-d414-11e9-8008-8226024d5985.png)
![screenshot-2](https://user-images.githubusercontent.com/25375330/64652972-ae498900-d414-11e9-8f28-d026ea1d6181.png)
![screenshot-3](https://user-images.githubusercontent.com/25375330/64652973-aee21f80-d414-11e9-888b-336c565cc749.png)

**Comment by jingyu9575** [comment]
This server is configured incorrectly. It says multithreading is supported, but rejects any attempts of multithreading.

You can see the effects, by downloading the link using the built-in download manager, and pause it in the middle. Resuming this download will cause failures.
