### ISSUE TITLE
[Feature request] prevent PC from sleep while downloading

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#85]
I'm not sure if this feature could be added or not. If it is possible, then it will be great if you add it.

I'm on Fedora Linux 30 X 64 bit with Firefox.

**Comment by jingyu9575** [comment]
Probably possible by playing an empty video in the background. I'll try it.

**Comment by Nokia808** [comment]
@jingyu9575 
I will test this. But the problem is how can I judge in case of "server error" at middle of download ? However, I trust you. Many thanks for your very hard work & super fast response !

**Comment by jingyu9575** [comment]
"Server error" means the server rejects your download. If the network is interrupted, the error will be "network error".

Try resuming the download; if another server error shows, you know that the server won't reconsider about the rejection.
