### ISSUE TITLE
Failure to automatically grab archive file !

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#86]
Hi.
I detect that your extension fail to automatically grab archive file from following site:
https://www.apunkasoftware.net/vlink/08034723540

It go directly to browser's built-in downloader.

For your kind fix.

**Comment by jingyu9575** [comment]
Looks like this is a POST link that is redirected to a GET link. For some reason the extension failed to catch it. I'll have a check.

**Comment by jingyu9575** [comment]
Unfortunately Firefox still reports the link as POST after redirection. POST links cannot use multithreading safely, so it is difficult to fix here.

**Comment by Nokia808** [comment]
@jingyu9575 
Dear there MUST be a solution & a fix because XDM already fix it. I worked with XDM for about more than a year & it worked with such type of link without any problem.

I suggest on you to inspect XDM code & if it is useful, then you can re-open this & fix it.

XDM site:
http://xdman.sourceforge.net/
https://sourceforge.net/projects/xdman/

Please do not ignore. You did very well with other issue & if you fix this you will make something very helpful .....

**Comment by jingyu9575** [comment]
XDM does not differenciate POST and GET. IMHO this is dangerous because POST requests often have side effects and not safe to repeat. Users do not want to multithreading a bank transfer request and end up transfering 4x money.

However, it seems possible to analyse the redirection and makes exceptions for POST links after redirection. I'll have a try.

**Comment by Nokia808** [comment]
@jingyu9575 
I do not know what I have to say ! I was of very litle hope that you can fix it, but now I test your patch & it working ! I update extension & test it. It working like XDM & uget ! You really serve Linux users by this extension ......
