### ISSUE TITLE
[Feature request] Add support for grabbing of videos from Youtube & other sites

### ISSUE THREAD

**Issue by Nokia808** [jingyu9575/multithreaded-download-manager#89]
Hi. Currently your nice extension can not grab videos on Youtube & other sites.

XDM can do this by display a bar (or icon) for download over the video, by clicking it the XDM will download the vidoe file. And in case of multiple files per single video (each with different resolution), it will show these files to make user select what she/he prefer. 

You can either:
1) make approach smiler to that of XDM,
or
2) make an icon within your extension GUI beside already existing (create a download task | import tasks from built-in download list | clear completed task | Options), so that clicking this new icon will lead to grab video file(s) on the visited page, so that if there are more than 1 file, then the user will have to select which one she/he prefer.
Let we name this new icon "grab video files"

If you add this feature it will be very useful.

Please if you like to add this feature, then not limit it to Youtube, but make it for any page.

**Comment by Nokia808** [comment]
@jingyu9575 
Hi again. 

I noticed that your extension already express "Download with multithread-download manager" option in right click list ! So, we need no further design (neither 1 nor 2 that I suggested in my 1st comment).

The current shortages with this right click option are 2:
1) it is currently not appeared on (over) all videos ..... An example is Yutetube.
2) on certain sites, right click option appeared on videos but when used it will download .php page not the video file(s)

For more explanation & tests: there is a porno site (I mention here just for testing purpose because we can improve your extension to very superior level if you fix it), this site called "Porn Hub". By default, this site not allow download unless sign in to it (you have to register an account on it). Even if you registered & login some time it asking for money to download ........ But both XDM & uget can cache video file(s) (if you installed corresponding Firefox add on of uget/XDM). Moreover, this site express in most cases more than single files (each with different resolution & even different format) per each single video. Both uget & XDM allow user to select from list of these files which one need to download.
But your extension if click on specific video to play it, then right click menu currently do not show "Download with MTD" option. And beside this videos appear small thumbnails for other videos if you just put your mouse (without click) they will play sample. But when right click such thumbnails, then right click menu will show "Download with MTD" option but on trying it it will download a .php file ! There is an extension for Firefox called "Adult Downloader" can grab correctly (without login nor payment) from "Porn Hub") !!! See this extension it may help you to fix for this site .....

I suggest the following:
1) ignore my suggestions in my 1st comment about design (1) & (2),
2) mentain current right click menu option for MTD,
3) make current right click menu option for MTD appear over any video in any page in any site,
4) make current right click menu option for DTM grab correct video file(s) not .php page,
5) make use of current right click menu option for MTD show all files available per single video in case if there are more than single file per single video, so that user can select from them ....

Please notice that I mention "Porn Hub" because I have previous experience that such sites are excellent to test ddownloader programs & add-on like your extension so that if working correctly with such sites then it will working okay with other usual sites .....

**Comment by jingyu9575** [comment]
> GNU version 2 license so that you can utilize & integrate it's code freely

No, it is not compatible with MPL that my extension is under. 

It also does not work on YouTube here. This task is very difficult and requires constant update, while that extension has not updated for a year.

**Comment by Nokia808** [comment]
@jingyu9575 
Not working with Youtube ?? It work we me ! Please can you give me Youtube links that not working with them from your side ?

**Comment by jingyu9575** [comment]
It works now. Not sure what was happening. However, the license is still an issue.

**Comment by Mike-Reddick** [comment]
this extension can work without maintenance because I think it use Youtube API, like uget download manager, but using official download API, you can just download 360p with audio, not 720p etc

**Comment by jingyu9575** [comment]
@Mike-Reddick I think there is no official download API for YouTube. Google [does now allow](https://law.stackexchange.com/a/1650) that in their terms of service. Userscripts can use hidden URLs for 360p download, but they break from time to time and need maintenance.

If you only want 360p I suggest installing such userscripts to show the hidden download URL.

**Comment by Nokia808** [comment]
@jingyu9575 
Hi. I discovered 2 add-on, well maintained, please look to them:

1) YouTube Video and Audio Downloader (Dev. Edt.):
https://technologyto.com/extractor.html
https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/

2) Download Video and Flash - HD Download:
https://addons.mozilla.org/en-US/firefox/addon/download-video-and-flash/

Both are well maintained & both have the same license as your your great add-on. So, no license problem.

1st add-on is ONLY working for YouTube, while 2nd is GLOBAL for any video (YouTube & non-YouTube). But 1st add-on is verified & recommended by  Mozilla, while 2nd add-on not verified by Mozilla.

From my side I see 2nd add-on (Download Video and Flash - HD Download) is better because it is more global.

**Comment by Nokia808** [comment]
@jingyu9575 
Dear, after extensive use, I found that "Download Video and Flash - HD Download) is really the best choice ! It support 360p & 720p.

I suggested the following (to make no additional hard task on your behalf): Just, & only just, add the following new option [grab from "Download Video and Flash - HD Download"]. You can add a notification beside this new option [You have to install "Download Video and Flash - HD Download"].

When user check this option, your add-on will grab from "Download Video and Flash - HD Download" if already installed. Your add-on already has the following option "enable prompt for links without multithreading support", if user not check this already existing option then new option that I suggested will only grab from "Download Video and Flash - HD Download" the links that support multithreaded download. But if user check "enable prompt for links without multithreading support" then your addon will grab from "Download Video and Flash - HD Download" even links that not support multithreading download.

What is your opinion ?

**Comment by jingyu9575** [comment]
So it seems that the feature requested by #119 can help. Extensions cannot see whether other extension's downloads support multithreading though.

**Comment by jingyu9575** [comment]
The feature in #119 is added in v2.8b1. Please see if it works for your use case.

**Comment by Nokia808** [comment]
@jingyu9575 
I do not know what I have to say !! Thank you ?! Excellent ?! All these words are not enough to evaluate what you did !! You save us from wasting our time in searching & configuration programs like "Internet download manager", "Accelerated download plus", uGet, XDM, .......

Now your add-on should be labeled as "Recommended" by Mozilla ......
