### ISSUE TITLE
[建议] 从扩展的下载列表删除后不要同时从Firefox下载列表删除

### ISSUE THREAD

**Issue by weijarz** [jingyu9575/multithreaded-download-manager#94]
比如这个使用流程：

1）从Firefox内置下载列表导入到扩展下载，任务会自动从Firefox下载列表删除（这个应该删除）。
2）扩展下载完后成保存，Firefox下载列表中有下载完成的条目。
3）从扩展列表中删除下载完的条目。
4）这时Firefox下载列表里也没有了刚才下载完的条目，无法点击打开对应的文件。

不知是不是有意设计成同步删除还是Firefox的限制，建议还是不要同步删除，因为过后找不到下载完的历史文件列表了。

**Comment by jingyu9575** [comment]
是有意设计。v2.2 添加选项“删除任务时删除对应内建下载项”，默认开启。
