### ISSUE TITLE
[Feature request] Download Queue and Batch Downloading

### ISSUE THREAD

**Issue by Zaturi** [jingyu9575/multithreaded-download-manager#96]
Thank you for this quite simple and easy-to-use download manager!

I've got two feature request questions for you:
1. Is it possible to add a download queue to this extension? Doesn't need to be anything fancy, I just want to add a bunch of links but I don't want them all to start immediately. The download manager should just work its way down the list. Optionally depending on a setting on how many simultaneous downloads are allowed. 
2. Is it possible to add a batch download feature to this extension? What I mean is something like DownThemAll currently provides, where I can add a link but add a pattern to it. For example if I wanted to download "Picture 001" to "Picture 100" instead of adding 100 links the the download manager I could just write the link as "Picture [001:100].jpg" and it would fetch all 100 links at once.

The batch download might be a bit more work than the download queue so I would already be extremely happy with just having the download queue in this awesome extension. Thanks again for you hard work, very appreciated!

**Comment by jingyu9575** [comment]
If my understanding is right these features already exist:

> add a download queue

Set the "simultaneous download tasks" option in the "General" tab of the extension settings. 

> batch download feature

`[001:100]` is supported in the "create a download task" dialog.
