### ISSUE TITLE
不支持网易云附件

### ISSUE THREAD

**Issue by ivysrono** [jingyu9575/multithreaded-download-manager#97]
这个很难给测试链接，不知作者有没有网易邮箱可以给自己发一个？

**Comment by jingyu9575** [comment]
测试发现不支持断点续传，所以默认不会提示。如果选中“允许提示不支持多线程下载的链接”，则可以使用1个线程下载。

**Comment by ivysrono** [comment]
文件名不对吧？

**Comment by jingyu9575** [comment]
文件名使用了非标准RFC2047编码。已修复，我先测试几次再更新。
