### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Mike-Reddick** [jingyu9575/multithreaded-download-manager#98]
Please add an changelog to plugin updates in mozila store. At last the main changes.

**Comment by jingyu9575** [comment]
I've added the changes from v2.1 to v2.4.

The extension was rewritten from v1.9 to v2. Almost all the code and UI were rebuilt, so it is not easy to have a summerized change list.

**Comment by Mike-Reddick** [comment]
right, I said about add an changelog of the main changes, like:

Plugin code fully re-writed
Added setting to choose something

thanks!
